-- MySQL Script generated by MySQL Workbench
-- Mon Jan 29 09:30:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfeuille
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `portfeuille` ;

-- -----------------------------------------------------
-- Schema portfeuille
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfeuille` DEFAULT CHARACTER SET utf8 ;
USE `portfeuille` ;

-- -----------------------------------------------------
-- Table `portfeuille`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfeuille`.`user` ;

CREATE TABLE IF NOT EXISTS `portfeuille`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` TEXT NOT NULL,
  `token` TEXT NULL,
  `cookieSecure` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `portfeuille`.`compte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfeuille`.`compte` ;

CREATE TABLE IF NOT EXISTS `portfeuille`.`compte` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `montant` INT NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Compte_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Compte_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `portfeuille`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfeuille`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfeuille`.`category` ;

CREATE TABLE IF NOT EXISTS `portfeuille`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` INT NOT NULL,
  `icon` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Category_User1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Category_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `portfeuille`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfeuille`.`budget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfeuille`.`budget` ;

CREATE TABLE IF NOT EXISTS `portfeuille`.`budget` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `montant` INT NOT NULL,
  `rollover` TINYINT NOT NULL,
  PRIMARY KEY (`id`, `category_id`, `user_id`),
  INDEX `fk_budget_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_budget_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_budget_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `portfeuille`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_budget_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `portfeuille`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfeuille`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfeuille`.`transaction` ;

CREATE TABLE IF NOT EXISTS `portfeuille`.`transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `compte_id` INT NULL,
  `montant` INT NOT NULL,
  `type` INT NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `commentaire` TEXT NULL,
  `toaccount` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transaction_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_transaction_compte1_idx` (`compte_id` ASC) VISIBLE,
  INDEX `fk_transaction_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `portfeuille`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_compte1`
    FOREIGN KEY (`compte_id`)
    REFERENCES `portfeuille`.`compte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `portfeuille`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfeuille`.`objectif`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfeuille`.`objectif` ;

CREATE TABLE IF NOT EXISTS `portfeuille`.`objectif` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `compte_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `title` TEXT NOT NULL,
  `montant` INT NOT NULL,
  `date_cible` DATETIME NOT NULL,
  `montant_touch` TINYINT NOT NULL,
  PRIMARY KEY (`id`, `compte_id`, `user_id`),
  INDEX `fk_Objectif_compte1_idx` (`compte_id` ASC) VISIBLE,
  INDEX `fk_objectif_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Objectif_compte1`
    FOREIGN KEY (`compte_id`)
    REFERENCES `portfeuille`.`compte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_objectif_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `portfeuille`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfeuille`.`facture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfeuille`.`facture` ;

CREATE TABLE IF NOT EXISTS `portfeuille`.`facture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `compte_id` INT NOT NULL,
  `montant` INT NOT NULL,
  `repetition` TINYINT NOT NULL,
  `date` DATETIME NOT NULL,
  `title` TEXT NOT NULL,
  `auto` TINYINT NOT NULL,
  `status` TINYINT NOT NULL,
  `rappel` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_facture_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_facture_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_facture_compte1_idx` (`compte_id` ASC) VISIBLE,
  CONSTRAINT `fk_facture_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `portfeuille`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facture_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `portfeuille`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facture_compte1`
    FOREIGN KEY (`compte_id`)
    REFERENCES `portfeuille`.`compte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
